Changed older versions button to links
mozilla/addons-frontend pull request #10237
Opened 2021-03-18 21:12 UTC by smitbarmase

Fixes #9811

This contains fixes from @sarthakkundra from #9973 and tests from @smitbarmase from #10098 

Recent changes contain:
1. Added test to verify that the `AMInstallButton` is not displayed, in older versions on Firefox browser.
2. Omit the property `showLinkInsteadOfButton` when it is false.
3. Versions page using a non-Firefox browser, no longer show "download Firefox" buttons for each version.

I refactored the code a bit to fix it and make it look cleaner and more understandable.

I have fixed all the bugs suggested in #10181 

@bobsilverberg PR is ready for review!

2021-03-25 12:49 UTC, bobsilverberg requested changes
Looks good, nice updates @smitbarmase! I just added a few comments about the tests.

2021-03-25 12:49 UTC, bobsilverberg commented on tests/unit/amo/components/TestInstallButtonWrapper.js
> +    const showLinkInsteadOfButton = false;
You don't really need a `const` for this. You could just include `showLinkInsteadOfButton: false` on line 344 below.

2021-03-25 12:49 UTC, bobsilverberg commented on tests/unit/amo/components/TestInstallButtonWrapper.js
> +    const showLinkInsteadOfButton = true;
As above, we don't really need this `const`.

2021-03-25 12:49 UTC, bobsilverberg commented on tests/unit/amo/components/TestInstallButtonWrapper.js
> +    const showLinkInsteadOfButton = true;
As above, no need for this `const`.

2021-03-25 19:20 UTC, smitbarmase commented
@bobsilverberg I have made the changes.

2021-03-26 12:26 UTC, bobsilverberg requested changes
Thanks for the updates @smitbarmase, they look good. I did notice one problem on the all versions page, though. The "Download file" link is left justified with the button for the latest version, but right justified in the column for the rest, which looks a bit ugly. Can you see if you can fix that? Please be sure to not change the way it looks on the add-on detail page, though.

Here's an example:

![Screen Shot 2021-03-26 at 8 25 59 AM](https://user-images.githubusercontent.com/142755/112631175-ee146d80-8e0c-11eb-940e-f053ba4da5fe.png)

2021-03-31 18:46 UTC, bobsilverberg commented
@smitbarmase Just checking in to see if you think you can address the comment added above. Thanks!

2021-03-31 21:46 UTC, smitbarmase commented
@bobsilverberg Yes, I can. I was quite busy this week as I have exams. Sorry for that.

One thing more, while running the project on the local server, it does not load SCSS files. So any styling does not appear on the window. All I see is HTML. I don't know why this is happening. Any suggestions?

I'm using WSL 2 on Windows 10.

2021-04-01 15:16 UTC, bobsilverberg commented
> @bobsilverberg Yes, I can. I was quite busy this week as I have exams. Sorry for that.
> 
> One thing more, while running the project on the local server, it does not load SCSS files. So any styling does not appear on the window. All I see is HTML. I don't know why this is happening. Any suggestions?
> 
> I'm using WSL 2 on Windows 10.

I'm not sure what might be causing that. Can you post any messages you see in the browser console that might indicate what the problem is?

2021-04-08 15:49 UTC, bobsilverberg commented
@smitbarmase We have another change landing next week that will really benefit from having this in place. Are you able to address the final concern raised? If not, then I can make the final changes and land this.

2021-04-09 05:26 UTC, smitbarmase commented
Here is what I'm getting. No CSS files have loaded. And there is one error in the console.

Browser console:
![image](https://user-images.githubusercontent.com/37347831/114132340-c56a9880-9921-11eb-82da-689473192042.png)

Screenshot:
![image](https://user-images.githubusercontent.com/37347831/114132197-889ea180-9921-11eb-88a9-66b67f7584a5.png)

I can't see any type of error in node console tough.

Node console:
```
[0] orphan modules 43.8 KiB [orphan] 29 modules
[0] runtime modules 31.1 KiB 16 modules
[0] modules by path ./src/ 7.08 MiB
[0]   modules by path ./src/amo/ 3.06 MiB 513 modules
[0]   modules by path ./src/locale/ 4.01 MiB 126 modules
[0]   modules by path ./src/fonts/ 12.5 KiB
[0]     modules by path ./src/fonts/woff2/*.woff2 840 bytes 10 modules
[0]     modules by path ./src/fonts/otf/*.otf 656 bytes 8 modules
[0]     modules by path ./src/fonts/*.scss 11 KiB
[0]       ./src/fonts/inter.scss 1.61 KiB [built] [code generated]
[0]       ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js!./src/fonts/inter.scss 9.38 KiB [built] [code generated]
[0] modules by path ./node_modules/ 3.31 MiB 493 modules
[0] ./src/locale/ sync ./node_modules/bundle-loader/index.js?name=[name]-i18n-[folder]! ^\.\/.*?\/amo\.js$ 1.18 KiB [built] [code generated]
[0] webpack 5.17.0 compiled successfully in 55273 ms
[1] [1617945375746404400] INFO  (amo/947 on comet): 🔥 Addons-frontend server is running [ENV:development] [isDevelopment:true] [isDeployed:false] [apiHost:http://localhost:3000] [apiPath:/api/] [apiVersion:v5]
[1] [1617945375748492300] DEBUG (amo/947 on comet): 🚦 Proxy detected, frontend running at http://127.0.0.1:3333.
[1] [1617945375748664600] DEBUG (amo/947 on comet): 👁  Open your browser at http://127.0.0.1:3000 to view it.
[1] 👀 The file watcher for server hot reload is ready.
```

2021-04-12 12:45 UTC, bobsilverberg commented
@smitbarmase What URL are you visiting when trying to load the site locally in your browser?

2021-04-15 19:09 UTC, bobsilverberg commented
@smitbarmase It would be nice to land this change for next week, so just wondering if you are able to address the last comment on it. If you don't think you'll have time I can finish it off for you.

2021-04-16 02:50 UTC, smitbarmase commented
@bobsilverberg Sure. Thank you for that :)

2021-04-20 15:33 UTC, bobsilverberg commented
This was replaced by #10401

2021-04-20 15:33 UTC, closed without merging