10351 add bug reporting information to about page
mozilla/addons-frontend pull request #10392
Opened 2021-04-15 11:09 UTC by pranav1601

Fixes #10351

add bug reporting information to about page
![after](https://user-images.githubusercontent.com/30745115/114859981-11797980-9e09-11eb-9188-ab9c5f91769d.png)
![before](https://user-images.githubusercontent.com/30745115/114859986-13433d00-9e09-11eb-86cf-086143f10b38.png)

2021-04-15 12:33 UTC, bobsilverberg requested changes
This looks good, thanks @pranav1601. The changes to `.husky/pre-commit` should not be included in this patch. I'm not sure what caused those changes.

2021-04-15 12:33 UTC, bobsilverberg commented on src/amo/pages/StaticPages/About/index.js
> +          <section>
The issue requested that an `id` attribute be added to this new section.

2021-04-15 12:59 UTC, pranav1601 commented
hey @bobsilverberg , 
I was getting an error when i was trying to commit saying .husky/pre-commit not found. I have fixed it now and I have committed it as well.
Thanks!

2021-04-15 15:20 UTC, bobsilverberg requested changes
Thanks @pranav1601. The `.husky/pre-commit` still needs to be dealt with.

2021-04-15 15:20 UTC, bobsilverberg commented on .husky/pre-commit
> +flow && lint-staged
It's still detecting a difference because this file is missing a new line at the end. This patch shouldn't contain any changes to `.husky/pre-commit`

2021-04-15 16:35 UTC, pranav1601 commented
Hey @bobsilverberg ,
didnt see that new line! Corrected it now though. Please review it.
Thanks!

2021-04-15 17:33 UTC, bobsilverberg approved these changes
Looks good, nice work @pranav1601! Thanks for the patch.

2021-04-15 17:33 UTC, merged

2021-04-15 17:56 UTC, pranav1601 commented
Thanks @bobsilverberg !

2021-04-16 21:13 UTC, caitmuenster commented
Yay, thank you so much, @pranav1601! 🎉Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Hope to see you around the project in the future!