RE: Add addonType property to homepage shelves
mozilla/addons-frontend pull request #10439
Opened 2021-04-19 21:19 UTC by xlisachan

Fixes #10438
In relation to #10357
Companion to [#16967](https://github.com/mozilla/addons-server/pull/16967)

This pull requests adds the `addonType` property to the homepage shelves in order to help differentiate the types of add-ons each shelf includes. In addition, it will handle the number of add-ons displayed across its shelf.

Note, I added '0' as default for now, which is not an integer used to describe any add-ons over on addons-server (1='Extension', 10='Theme (Static)').

The following files have been updated:
- `components/HomepageShelves/index.js`
- `amo/reducers/home.js`
- `tests/unit/amo/components/TestHomepageShelves.js`
- `tests/unit/amo/reducers/test_home.js`
- `tests/unit/helpers.js`

@bobsilverberg, please review when you have a moment. Thank you!

2021-04-20 19:52 UTC, bobsilverberg requested changes
It looks good, thanks for your efforts on this @xlisachan.

I think the only changes needed are the ones we discussed in the meeting. I've left detailed comments.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/components/HomepageShelves/index.js
> +export const HOMESHELVES_ADDON_TYPE_EXTENSIONS = 1;
As discussed, you don't need a new `const` for this. You can just use `ADDON_TYPE_EXTENSION`.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/components/HomepageShelves/index.js
> +export const HOMESHELVES_ADDON_TYPE_THEMES = 10;
As above, this can be `ADDON_TYPE_STATIC_THEME`.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/components/HomepageShelves/index.js
> +      const themeBool =
`hasThemes` is a bit more readable and consistent with our codebase than `themeBool`.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/reducers/home.js
> +  addonType: number,
As discussed, this should be a string, and in fact we have an `AddonTypeType` which can be used here.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/reducers/home.js
> +  addonType: number,
As above, use `AddonTypeType`.

2021-04-20 19:52 UTC, bobsilverberg commented on src/amo/reducers/home.js
> +    addonType: result.addonType || 0,
You shouldn't need the `|| 0` here, as without it `addonType` will end up with a `null` which should work. Flow might complain and if it does you'll need to change the type above to `AddonTypeType | null`.

2021-04-20 19:52 UTC, bobsilverberg commented on tests/unit/amo/components/TestHomepageShelves.js
> +      addonType: 1,
As discussed, use the string consts here and in the next one as well.

2021-04-20 19:52 UTC, bobsilverberg commented on tests/unit/amo/components/TestHomepageShelves.js
> +    [false, HOMESHELVES_ENDPOINT_COLLECTIONS, 0],
It feels a bit overboard with all the combinations, but I guess for now every path needs to be tested. Please open an issue to remove the code that bases this on `endpoint` after the server change lands, and then we can clean up these tests as well.

2021-04-20 19:52 UTC, bobsilverberg commented on tests/unit/amo/reducers/test_home.js
> +        addonType: 10,
Use string const.

2021-04-20 19:52 UTC, bobsilverberg commented on tests/unit/helpers.js
> +  addonType: 10,
Use string const.

2021-04-21 14:23 UTC, bobsilverberg requested changes
Looks good, thanks for the update @xlisachan! As mentioned below, I don't think we need `HOMESHELVES_ADDON_TYPE_EXTENSIONS` or `HOMESHELVES_ADDON_TYPE_THEMES` at all.

2021-04-21 14:23 UTC, bobsilverberg commented on src/amo/components/HomepageShelves/index.js
> +export const HOMESHELVES_ADDON_TYPE_EXTENSIONS = ADDON_TYPE_EXTENSION;
I don't think we need these `const`s. We can just use `ADDON_TYPE_EXTENSION` and `ADDON_TYPE_STATIC_THEME` directly in the code. We do that everywhere else.

2021-04-21 14:23 UTC, bobsilverberg commented on src/amo/components/HomepageShelves/index.js
> +        addonType === HOMESHELVES_ADDON_TYPE_THEMES;
As mentioned above, use `ADDON_TYPE_STATIC_THEME` here.

2021-04-21 14:23 UTC, bobsilverberg commented on tests/unit/amo/components/TestHomepageShelves.js
> +      HOMESHELVES_ADDON_TYPE_EXTENSIONS,
As mentioned above, just use `ADDON_TYPE_STATIC_THEME` and `ADDON_TYPE_EXTENSION` directly. This goes for all the code in this test suite.

2021-04-21 14:48 UTC, xlisachan commented
Makes sense, @bobsilverberg! The latest push removes the `const`s. Please review when you have a moment. Thank you!

2021-04-21 14:54 UTC, bobsilverberg approved these changes
Looks good, nice work @xlisachan! Thanks for taking care of this so quickly!

2021-04-21 14:55 UTC, merged